grails-app/domain/roomzik/Artista.groovy
package roomzik

class Artista extends Persona{
    int premium
    Set<Musica> creaciones = []
    Set<Playlist> albums = []
    static hasMany = {
        creaciones : Musica
        albums : Playlist
    }
    static constraints = {
    }
    Musica addCreacion(Musica creacion){
    	creaciones.add(creacion)
    }
    Playlist addAlbum(Playlist album){
    	albums.add(album)
    }

    String toString(){
        "nombre "+nombre+"\npremium "+premium+"\nid\n\n"+id
    }
}

grails-app/domain/roomzik/Estilo_de_musica.groovy
package roomzik

class Estilo_de_musica {
    String nombre
    static constraints = {
    }
}

grails-app/domain/roomzik/Melomano.groovy
package roomzik

class Melomano extends Persona {
    Set<Melomano> amigos = []
    String email
    Set<Musica> gustos = []
    Set<Playlist> playlists = []
    Set<Publicacion> noticias = []
    Set<Artista> artistas_siguidos = []
    static hasMany = {
        amigos : Melomano
        gustos : Musica
        artistas_siguidos : Artista
        noticias : Publicacion
        playlists : Playlist
    }
    static constraints = {
    }

    String toString(){
        "nombre : "+nombre+"\nemail : "+email
    }
}

grails-app/domain/roomzik/Musica.groovy
package roomzik

class Musica {
    String nombre
    Set <Estilo_de_musica> estilos = []
    Set <Artista> artistas = []
    long escuchas
    String path 
    String musicaContentType 

    static constraints = {
        musicaContentType nullable: true
    }

    static mapping = {
        musicaBytes column: 'musica_bytes', sqlType: 'longblob' 
    }
    static belongsTo = [artistas: Artista]
    static hasMany = {
        estilos : Estilo_de_musica
        artistas : Artista
    }
}

grails-app/domain/roomzik/Persona.groovy
package roomzik

abstract class Persona {
    String nombre

    String toString(){
        "Persona: "+nombre
    }
}

grails-app/domain/roomzik/Playlist.groovy
package roomzik

class Playlist {
	String titulo
	Set <Musica> musicas = []
	Persona creador
	static hasMany = {
		musicas : Musica
	}
    static constraints = {

    }
}

grails-app/domain/roomzik/Publicacion.groovy
package roomzik


enum Tipo_publicacion {
		publicacion,
		artista,
		playlist,
		musica,
		normal
	}

class Publicacion {
	Persona editor
	String mensaje
	Tipo_publicacion tipo
    static constraints = {
    }
}

grails-app/domain/roomzik/Publicacion_artista.groovy
package roomzik

class Publicacion_artista extends Publicacion{
	Artista artista
    static constraints = {
    
    }
}

grails-app/domain/roomzik/Publicacion_musica.groovy
package roomzik

class Publicacion_musica extends Publicacion{
	Musica musica
    static constraints = {
    }
}

grails-app/domain/roomzik/Publicacion_playlist.groovy
package roomzik

class Publicacion_playlist extends Publicacion{
	Playlist playlist
    static constraints = {
    }
}

grails-app/domain/roomzik/Publicacion_publicacion.groovy
package roomzik

class Publicacion_publicacion extends Publicacion{
	Publicacion publicacion
    static constraints = {
    }
}

grails-app/controllers/roomzik/ArtistaController.groovy
package roomzik

class ArtistaController {
	def artistaService
    def index() { redirect(action:"consultar")}
    def newArtista(){
    	if (!params.nombre){
    	render(view: "newArtista")
    	}
    	else{	
    		def artista = new Artista(nombre: params.nombre,
    			premium: 1)
    		artistaService.save(artista)
	  		def allsArtista = Artista.getAll()
	  		redirect(action:'consultar')
    	}
    }
    def editMusicas(){
    	if(!params.artistaId){
    		redirect(action :"index")
    	}
    	def artistaId = params.artistaId
    	render(view: "../musica/addMusica",params:[artistaId:artistaId])
    }
    def consultar(){
    	if(params.artistaId){
    		Artista artista = Artista.get(params.artistaId)
    		[artistas: artista, cuantos:1]
    	}
    	else {
    		if(params.artistaIds){

    		}
    		else{
				Set<Artista> alls = Artista.getAll()
				[artistas:alls, cuantos:alls.size()]
			}
		}	 
	}
}

grails-app/controllers/roomzik/MelomanoController.groovy
package roomzik

class MelomanoController {
	def melomanoService
    def index() { }
    def newMelomano(){

    	if (!params.nombre){
    	render(view: "newMelomano")
    	}
    	else{
    		if(params.email){
	    		def melomano = new Melomano(nombre: params.nombre,
    				email: params.email)
    			melomanoService.save(melomano)
	  			def allsMelomanos = Melomano.getAll()
	  			render(allsMelomanos)
    		}
    	}
	}
	def consultarAll(){
		render(showMelomano)
		[melomanos: melomanoService.getAll()]
	}
}

grails-app/controllers/roomzik/MusicaCommand.groovy
package roomzik

import grails.validation.Validateable
import org.springframework.web.multipart.MultipartFile

class MusicaCommand implements Validateable {
    MultipartFile musicaFile
    Long id
    Integer version = 1
    
    static constraints = {
        id nullable: false
        version nullable: false
        musicaFile  validator: { val, obj ->
            if ( val == null ) {
                return false
            }
            if ( val.empty ) {
                return false
            }

            ['mp3'].any { extension -> 
                 val.originalFilename?.toLowerCase()?.endsWith(extension)
            }
        }
    }
}

grails-app/controllers/roomzik/MusicaController.groovy
package roomzik

class MusicaController {

	def musicaService
	def artistaService
    def index() { redirect(uri:"/")}
    def addMusica(MusicaCommand cmd){
    	if (!params.artistaId && !cmd){
    	//add a flash message to print on main page
    	redirect(uri: "/")
    	}
    	else{
        if (cmd == null) {
            notFound()
            return
        }

        if (cmd.hasErrors()) {
            respond(cmd.errors, model: [musica: cmd], view: 'error')
            return
        }
		String applicationPath = request.getSession().getServletContext().getRealPath("")
        def musica = musicaService.addMusica(cmd,applicationPath)

        if (musica == null) {
            notFound()
            return
        }

        if (musica.hasErrors()) {
            respond(musica.errors, model: [musica: musica], view: 'error')
            return
        }

        //request.withFormat {
         //   form multipartForm {
        //        flash.message = message(code: 'default.updated.message', args: [message(code: 'musica.label', default: 'musica'), musica.id])
        //        redirect musica
        //    }
        //    '*' { respond musica, [status: OK] }
        //}

        redirect action: 'consultar', params:[musicaId: musica.id]
    	}
    		//else{
    		//[artistaId:params.artistaId]
    		//}
    }
    
    def leer(Musica musica) {
        if (musica == null){
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }
        render file: musica.musicaBytes, contentType: musica.musicaContentType
    }
    def notFound(){
    	render "notFound"
    }
    
    def delete(){
    	if(params.musicaId){
    		Musica musica = Musica.get(params.musicaId)
    		musica.delete()
    			
    	}
    }
    def consultar(){
    	[musica :Musica.get(params.musicaId)]
    	//todo
	}
}

grails-app/controllers/roomzik/UrlMappings.groovy
package roomzik

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
       // "/newArtista"(controller: "Artista", action: "renderNewArtista")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/artista/consultar.gsp
<!doctype html>
<html>
<head>
	<g:set var="cuantos" value="${cuantos}" />
	<g:set var="artistas" value="${artistas}" />
</head>
<body>
	<g:if test="${cuantos == 0}">
		<div>
			No artistas, puedes anadir uno aca : <g:link action="newArtista"> link </g:link>
			<br>
			hay ${cuantos} artistas
			<br>
	</g:if>
	<g:else>
	<g:if test="${cuantos == 1}">
		<div class="title-body">
			${artistas.nombre}
		</div>
		<br>
		musics :
		${artistas.creaciones}
		<br>
		<div class="list-music">
			<g:each in="${artistas.creaciones}" var="musica">
				<h1>${musica.nombre}</h1>
				<br>
				${musica.musicaContentType}
				<br>
				<g:if test="${musica}">
                <audio controls>
  					<source src="<g:resource dir='audio' file='${musica.nombre}'/>" type="audio/mpeg">
  					
					Your browser does not support the audio element.
				</audio> 

				<br>
				<g:link controller="Musica" action="delete" params="[musicaId:musica.id]" >
				delete music
				</g:link>
				<br> 
            </g:if>
            <br>
			</g:each>
		</div>
		<br>
		<div class="add-music">
			<g:link controller="Artista" action="editMusicas" params="[artistaId: artistas.id]">
				Anadir una musica
			</g:link>
			<br>
		</div>
		puedes anadir un artista aca : <g:link action="newArtista"> link </g:link>
	</g:if>
    <g:else>
    	<div>
       		<bold>Consultar artistas</bold> <br>
    	</div>
    	<g:each in="${artistas}" var="artista">
    		<g:link controller="Artista" action="consultar" params="[artistaId:artista.id]"> 
    			${artista.nombre}
    		</g:link>
    		<br>
	    </g:each>
    </g:else>
    puedes anadir un artista aca : <g:link action="newArtista"> link </g:link>
		</g:else>
</body>
</html>

grails-app/views/artista/newArtista.gsp
<!doctype html>
<html>
<body>
    <div>
        Creacion de un nuevo Artista
    </div>
    <g:form action="newArtista">
        Nombre del artista : <input type="text" name="nombre">
    </g:form>
</body>
</html>

grails-app/views/artista/success.gsp
<!doctype html>
<html>
<body>
    <div>
       Success
</body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#">
                    <i class="fa grails-icon">
                        <asset:image src="grails-cupsonly-logo-white.svg"/>
                    </i> Grails
                </a>
            </div>
            <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                <ul class="nav navbar-nav navbar-right">
                    <g:pageProperty name="page.nav" />
                </ul>
            </div>
        </div>
    </div>

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/melomano/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'melomano.label', default: 'Melomano')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-melomano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-melomano" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.melomano}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.melomano}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.melomano}" method="POST">
                <fieldset class="form">
                    <f:all bean="melomano"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/melomano/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'melomano.label', default: 'Melomano')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-melomano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-melomano" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.melomano}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.melomano}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.melomano}" method="PUT">
                <g:hiddenField name="version" value="${this.melomano?.version}" />
                <fieldset class="form">
                    <f:all bean="melomano"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/melomano/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-melomano" class="skip" tabindex="-1"><g:message code="" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-melomano" class="content scaffold-list" role="main"   >
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${melomanoList}" />

            <div class="pagination">
                <g:paginate total="${melomanoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/melomano/newMelomano.gsp
<!doctype html>
<html>
<body>
    <div>
        Creacion de un nuevo Melomano
    </div>
    <g:form action="newMelomano">
        Nombre del melomano : <input type="text" name="nombre">
        <br>
        Email del melomano : <input type="text" name="email">
		<br>
		<input type="submit" value="Submit">
    </g:form>
</body>
</html>

grails-app/views/melomano/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'melomano.label', default: 'Melomano')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-melomano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-melomano" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="melomano" />
            <g:form resource="${this.melomano}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.melomano}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/musica/addMusica.gsp
<!doctype html>
<html>
<head>
	<g:set var="artistaId" value="${params.artistaId}" />
</head>
<body>
	<g:uploadForm name="addMusica" controller="Musica" action="addMusica">
	    <g:hiddenField name="id" value="${artistaId}" />
	    <g:hiddenField name="version" value="1" />
	    <input type="file" name="musicaFile" />
	    <fieldset class="buttons">
	        <input class="save" type="submit" value="${message(code: 'musica.upload.label', default: 'Upload')}" />
	    </fieldset>
	</g:uploadForm>
	
</body>
</html>

grails-app/views/musica/consultar.gsp
<!doctype html>
<html>
<head>
	<g:set var="musica" value="${musica}" />

</head>
<body>
	<h1>${musica.nombre}</h1>
	<br>
	${musica.id}
	<audio controls>
  					<source src="<g:resource dir='audio' file='${musica.nombre}'/>" type="audio/mpeg">
  					
					Your browser does not support the audio element.
				</audio> 

</body>
</html>

grails-app/views/musica/error.gsp
<!doctype html>
<html>
<head>
	
</head>
<body>
	error ; <br>
	${musica.errors}
	
</body>
</html>